/** Formules affichées au survol des indicateurs (KPI). */
export const METRIC_FORMULAS: Record<string, string> = {
  "Patrimoine brut": "Somme des valeurs estimées des SCI d’investissement (hors résidence principale).",
  "Dette restante": "Somme des CRD des crédits d’investissement (hors résidence principale).",
  "Patrimoine net": "Patrimoine brut − Dette restante (investissement uniquement).",
  "Loyers annuels": "Σ (loyer mensuel × 12) des biens d’investissement (hors RP).",
  "Cash-flow / mois": "Σ [Loyer − Mensualité crédit − Taxe foncière/12] sur l’investissement (hors RP).",
  "Rendement brut": "(Loyers annuels ÷ Patrimoine brut) × 100 — investissement uniquement.",
  "Rendement net": "((Loyers annuels − Taxe foncière − Assurance PNO) ÷ Patrimoine brut) × 100. Hors crédit, impôts et RP.",
  "Valeur actuelle": "Estimation de marché saisie pour le bien.",
  "Plus-value": "Valeur actuelle − (Prix d’achat + Travaux + Frais de notaire).",
  "Loyer mensuel": "Loyer hors charges, tel que saisi dans la fiche bien.",
  "Cash-flow mensuel": "Loyer − Mensualité crédit − Taxe foncière/12 − Assurance/12.",
  "Cash-flow bien": "Loyer − Mensualité crédit (hors assurance emprunteur) − Taxe foncière/12.",
  "Taxe foncière / an": "Montant annuel de taxe foncière saisi pour le bien.",
  "Assurance / an": "Prime annuelle d’assurance du bien (PNO, etc.).",
  "Coût total": "Prix d’achat + Travaux + Frais de notaire.",
  "Prix d'achat": "Prix d’acquisition hors frais.",
  "Montant emprunté": "Capital initial emprunté à la banque.",
  "Capital restant": "CRD à la date du jour, calculé via le tableau d’amortissement.",
  "Crédit restant": "Somme des CRD de tous les biens de l’entité.",
  "Mensualité crédit": "C × r / (1 − (1+r)^−n) avec r = taux annuel / 12 et n = durée en mois.",
  "Mensualité totale": "Mensualité crédit + Assurance emprunteur mensuelle.",
  "Assurance / mois": "Montant fixe mensuel d’assurance emprunteur (si renseigné).",
  "Intérêts totaux": "Somme des intérêts sur toute la durée du prêt (tableau d’amortissement).",
  Remboursé: "((Montant emprunté − CRD actuel) ÷ Montant emprunté) × 100.",
  "Fin de prêt": "Date de la dernière échéance du tableau d’amortissement.",
  "Taux annuel": "Taux nominal annuel du crédit (hors assurance).",
  "Taux": "Taux nominal annuel du crédit.",
  "Valeur estimée": "Estimation patrimoniale de l’entité (SCI ou RP).",
  "Loyers / mois": "Somme des loyers mensuels des biens rattachés à l’entité.",
  "Cash-flow": "Σ cash-flow mensuel de tous les biens de l’entité.",
  Biens: "Nombre de biens immobiliers rattachés à l’entité.",
  Régime: "Régime fiscal de la structure (IR, IS ou RP).",
  "Plus-value latente": "Valeur actuelle − Coût de revient (achat + travaux + notaire). Hors fiscalité et hors dette. Indisponible si le coût n’est pas saisi.",
  "Coût de revient": "Prix d’achat + Travaux + Frais de notaire.",
  "Gain %": "(Plus-value ÷ Coût de revient) × 100. Affiché seulement si le coût de revient est renseigné.",
  "Résultat net consolidé mensuel": "Σ (Loyers − Mensualité crédit − Ass. emprunteur − Taxe/12 − PNO/12 − Honoraires gestion).",
  "Loyers/mois": "Somme des loyers mensuels des locataires actifs.",
  Actifs: "Nombre de baux en cours ou à renouveler (hors terminés).",
  Impayés: "Nombre de locataires au statut « Impayé ».",
  "Part crédit": "CRD de la SCI × parts de l’associé connecté (ex. 50 % BENEDUC).",
  "Mensualités part": "Mensualités de la SCI × parts de l’associé.",
  "Part valeur": "Valeur estimée de la SCI × parts de l’associé.",
  "Ma part — brut": "Σ (valeur estimée SCI × % de parts) — SCI d’investissement uniquement, hors RP.",
  "Ma part — dette": "Σ (CRD SCI × % de parts) — hors résidence principale.",
  "Ma part — net": "Ma part brut − Ma part dette.",
  "Ma part — loyers/an": "Σ (loyers annuels SCI × % de parts) — hors RP.",
  "Ma part — cash/mois": "Σ (cash-flow mensuel SCI × % de parts) — hors RP.",
  "Ma part — mensualités": "Σ (mensualités crédit SCI × % de parts) — hors RP.",
  "Ma part — rdt brut": "(Ma part loyers/an ÷ Ma part brut) × 100.",
  "Ma part — rdt net": "((Ma part loyers/an − charges part) ÷ Ma part brut) × 100.",
  "Cash mensuel total": "Cash-flow mensuel net agrégé (loyers − charges − crédits).",
  "Valeur": "Estimation de marché actuelle du bien.",
  "Loyer/mois": "Loyer mensuel hors charges.",
  "Type": "Typologie et surface du bien (données saisies).",
  Mensualité: "Mensualité crédit calculée (hors assurance emprunteur).",
  "CRD projeté": "Capital restant dû total projeté à la date sélectionnée.",
};

export function metricFormula(label: string): string | undefined {
  return METRIC_FORMULAS[label];
}
