/** Formules affichées au survol des indicateurs (KPI). */
export const METRIC_FORMULAS: Record<string, string> = {
  "Patrimoine brut": "Somme des valeurs estimées de toutes les entités (SCI + résidence principale).",
  "Dette restante": "Somme des capitaux restants dus (CRD) sur l’ensemble des crédits immobiliers.",
  "Patrimoine net": "Patrimoine brut − Dette restante.",
  "Loyers annuels": "Σ (loyer mensuel × 12) pour tous les biens locatifs.",
  "Cash-flow / mois": "Σ [Loyer − Mensualité crédit − Taxe foncière/12 − Assurance/12] pour chaque bien.",
  "Rendement brut": "(Loyers annuels ÷ Patrimoine brut) × 100.",
  "Valeur actuelle": "Estimation de marché saisie pour le bien.",
  "Plus-value": "Valeur actuelle − (Prix d’achat + Travaux + Frais de notaire).",
  "Loyer mensuel": "Loyer hors charges, tel que saisi dans la fiche bien.",
  "Cash-flow mensuel": "Loyer − Mensualité crédit − Taxe foncière/12 − Assurance/12.",
  "Cash-flow bien": "Loyer − Mensualité crédit (hors assurance emprunteur) − Taxe foncière/12.",
  "Taxe foncière / an": "Montant annuel de taxe foncière saisi pour le bien.",
  "Assurance / an": "Prime annuelle d’assurance du bien (PNO, etc.).",
  "Coût total": "Prix d’achat + Travaux + Frais de notaire.",
  "Prix d'achat": "Prix d’acquisition hors frais.",
  "Montant emprunté": "Capital initial emprunté à la banque.",
  "Capital restant": "CRD à la date du jour, calculé via le tableau d’amortissement.",
  "Crédit restant": "Somme des CRD de tous les biens de l’entité.",
  "Mensualité crédit": "C × r / (1 − (1+r)^−n) avec r = taux annuel / 12 et n = durée en mois.",
  "Mensualité totale": "Mensualité crédit + Assurance emprunteur mensuelle.",
  "Assurance / mois": "Montant fixe mensuel d’assurance emprunteur (si renseigné).",
  "Intérêts totaux": "Somme des intérêts sur toute la durée du prêt (tableau d’amortissement).",
  Remboursé: "((Montant emprunté − CRD actuel) ÷ Montant emprunté) × 100.",
  "Fin de prêt": "Date de la dernière échéance du tableau d’amortissement.",
  "Taux annuel": "Taux nominal annuel du crédit (hors assurance).",
  "Taux": "Taux nominal annuel du crédit.",
  "Valeur estimée": "Estimation patrimoniale de l’entité (SCI ou RP).",
  "Loyers / mois": "Somme des loyers mensuels des biens rattachés à l’entité.",
  "Cash-flow": "Σ cash-flow mensuel de tous les biens de l’entité.",
  Biens: "Nombre de biens immobiliers rattachés à l’entité.",
  Régime: "Régime fiscal de la structure (IR, IS ou RP).",
  "Plus-value latente": "Valeur actuelle − Coût de revient (achat + travaux + notaire).",
  "Coût de revient": "Prix d’achat + Travaux + Frais de notaire.",
  "Gain %": "(Plus-value ÷ Coût de revient) × 100.",
  "Loyers/mois": "Somme des loyers mensuels des locataires actifs.",
  Actifs: "Nombre de baux en cours ou à renouveler (hors terminés).",
  Impayés: "Nombre de locataires au statut « Impayé ».",
  "Part crédit": "Quote-part du CRD total allouée à cette entité selon la répartition patrimoniale.",
  "Mensualités part": "Quote-part des mensualités de crédit pour cette entité.",
  "Cash mensuel total": "Cash-flow mensuel net agrégé (loyers − charges − crédits).",
  "Valeur": "Estimation de marché actuelle du bien.",
  "Loyer/mois": "Loyer mensuel hors charges.",
  "Type": "Typologie et surface du bien (données saisies).",
  Mensualité: "Mensualité crédit calculée (hors assurance emprunteur).",
  "CRD projeté": "Capital restant dû total projeté à la date sélectionnée.",
};

export function metricFormula(label: string): string | undefined {
  return METRIC_FORMULAS[label];
}
